name: Daily Script Execution

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.1.2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

   # - name: Set up R and Tidyverse
    #  uses: rocker-org/rocker-action@v2.2.0
     # with:
      #  r-version: "4.1.2"
       # rocker-version: "4.1.2"
        #tidyverse: "true"

    - name: Execute script 
      run: |
        Rscript update.R
    - name: Commit files # Commit changes
      run: |
        git config --global --add safe.directory /__w/starter-code-ogdtg/starter-code-ogdtg
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull
        git add .
        git diff-index --quiet HEAD || (git commit -m "update notebooks" && git push)
