name: Daily Script Execution

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.1.2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

   # - name: Set up R and Tidyverse
    #  uses: rocker-org/rocker-action@v2.2.0
     # with:
      #  r-version: "4.1.2"
       # rocker-version: "4.1.2"
        #tidyverse: "true"

    - name: Execute script and push results
      run: |
        Rscript update.R
        git config --global user.name "ogdtg"
        git config --global user.email "ogd@tg.ch"
        git add .
        git commit -m "Update results"
        git push
